services:
  masa-tee-worker:
    network_mode: "host"
    # image: masaengineering/tee-worker:main
    # Uncomment to build from source
    build: .
    env_file:
      - ./.masa/.env
    ports:
       - "${PORT:-8080}:${PORT:-8080}"
    environment:
      LISTEN_ADDRESS: ":${PORT:-8080}"
      # comment if running with Intel SGX HW
      OE_SIMULATION: "1"
      # SGX library logging level: NONE/ FATAL / ERROR / WARNING / INFO / VERBOSE
      OE_LOG_LEVEL: INFO
      LOG_LEVEL: DEBUG
      STANDALONE: true
    volumes:
      - ./.masa:/home/masa
    restart: always
    # uncomment if running with Intel SGX
    # devices:
    # - /dev/sgx_enclave
    # - /dev/sgx_provision
