services:
  masa-tee-worker:
    network_mode: "host"
    # image: masaengineering/tee-worker:main
    # Uncomment to build from source
    build: .
    env_file:
      - .env
    ports:
       - "8080:8080" # this is ignored when network_mode is host
    environment:
      LISTEN_ADDRESS: "${LISTEN_ADDRESS:-:8080}"
      # comment if running with Intel SGX HW
      OE_SIMULATION: "1"
      # SGX library logging level: NONE/ FATAL / ERROR / WARNING / INFO / VERBOSE
      OE_LOG_LEVEL: INFO
      LOG_LEVEL: DEBUG
      STANDALONE: true
    restart: always
    # uncomment if running with Intel SGX
    # devices:
    # - /dev/sgx_enclave
    # - /dev/sgx_provision
