services:
  masa-tee-worker:
    network_mode: "host"
    image: masaengineering/tee-worker:main
    # Uncomment to build from source
    # build: .
    ports:
       - "8080:8080"
    environment:
      LISTEN_ADDRESS: ":8080"
      # uncomment if not running with Intel SGX HW
      # OE_SIMULATION: "1"
      # SGX library logging level: NONE/ FATAL / ERROR / WARNING / INFO / VERBOSE
      OE_LOG_LEVEL: INFO
      LOG_LEVEL: info
    volumes:
      - ./.env:/home/masa/.env
    restart: always
    # uncomment if running with Intel SGX
    # devices:
    # - /dev/sgx_enclave
    # - /dev/sgx_provision
