name: Run Go Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      env:
        TWITTER_TEST_ACCOUNT: ${{ secrets.TWITTER_TEST_ACCOUNT }}
      run: |
        make test
        sudo mv coverage/coverage.txt coverage.txt
        sudo chmod 777 coverage.txt
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}