name: Run Go Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Install golangci-lint
      run: sudo snap install golangci-lint --classic

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v5
      with:
        go-version-file: go.mod

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Run tests
      run: |
        go mod tidy && git diff --exit-code
        go mod download
        go mod verify
        gofmt -s -w . && git diff --exit-code
        go vet ./...
        golangci-lint run

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v5
      with:
        go-version-file: go.mod
          
    - name: Run unit tests
      run: |
        go test ./...

  ready-to-merge:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify that merging is OK
        run: |
          if grep -rE 'DO[ ]NOT[ ]MERGE|[F]IXME' .; then
              exit 1
          fi
